main: GlobalBan\Main
api: 1.13.0
name: GlobalBans
author: korado531m7
version: 2.1.0
description: Global Banning System Plugin
commands:
 gban:
  description: Globan Banning Plugin Command
  permission: gban.command
permissions:
 gban.command:
  description: No Description for Permission which this plugin
  default: op